### ISSUE TITLE
请问后台默认账号密码是什么？

### ISSUE THREAD

**Issue by lookoupai** [z719893361/tg-bot#1]
docker启动后不知道该怎么登录后台，小白不太会用。。。

**Comment by z719893361** [comment]
> docker启动后不知道该怎么登录后台，小白不太会用。。。

抱歉，记录了一下烂尾项目，使您感到了困扰。项目只实现了一些简单的功能。部分功能还没添加，目前还没有添加初始账号。

你可以修改docker-compose.yaml文件，在db服务中添加ports字段。配置如下

```
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tg-robot
      MYSQL_USER: tg
      MYSQL_PASSWORD: dfBXdfK02UbyU7ZH
      MYSQL_ROOT_PASSWORD: dfBXdfK02UbyU7ZH
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: dockerfile/python
    container_name: web
    restart: always
    environment:
      MYSQL_URL: 'mysql+aiomysql://tg:dfBXdfK02UbyU7ZH@db:3306/tg-robot'
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
```
修改后执行`docker-compose up -d` 命令更新容器后，可以使用navicat等工具连接数据库。

连接数据库后应该可以看到admin表，在里面添加即可
